<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 6.0.4 on 2026-05-02 01:32
=======
# Generated by Django 5.2.13 on 2026-04-29 06:09
>>>>>>> origin/dev-lina
=======
# Generated by Django 6.0.4 on 2026-05-16 13:42
>>>>>>> origin/dev-alqan
=======
# Generated by Django 6.0.4 on 2026-05-02 01:32
>>>>>>> origin/dev-lina

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventori', '0002_proyek_role_teknologi_projectrole_roleteknologi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BobotKriteria',
            fields=[
                ('id_bobot', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nilai_bobot', models.FloatField()),
                ('nilai_swara', models.FloatField(blank=True, null=True)),
                ('versi', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role_teknologi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventori.roleteknologi')),
            ],
            options={
                'db_table': 'dss_bobotkriteria',
            },
        ),
        migrations.CreateModel(
            name='DSSProses',
            fields=[
                ('id_dss', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('role_dss', models.CharField(max_length=100)),
                ('jenis_dss', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('id_bobot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.bobotkriteria')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.user')),
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
                ('bobot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.bobotkriteria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.user')),
>>>>>>> origin/dev-alqan
            ],
            options={
                'db_table': 'dss_dssproses',
            },
        ),
        migrations.CreateModel(
            name='HasilSAW',
            fields=[
                ('id_hasil', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tanggal_proses', models.DateTimeField(auto_now_add=True)),
                ('dss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.dssproses')),
            ],
            options={
                'db_table': 'dss_hasilsaw',
            },
        ),
        migrations.CreateModel(
            name='DetailHasilSAW',
            fields=[
                ('id_detail', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nilai_normalisasi', models.FloatField()),
                ('nilai_preferensi', models.FloatField()),
                ('ranking', models.IntegerField()),
                ('hasil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_set', to='dss.hasilsaw')),
            ],
            options={
                'db_table': 'dss_detailhasilsaw',
            },
        ),
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id_kriteria', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nama_kriteria', models.CharField(max_length=255)),
                ('tipe_kriteria', models.CharField(choices=[('benefit', 'Benefit'), ('cost', 'Cost')], max_length=20)),
                ('golongan_kriteria', models.CharField(max_length=255)),
                ('teknologi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventori.teknologi')),
            ],
            options={
                'db_table': 'dss_kriteria',
            },
        ),
        migrations.AddField(
            model_name='bobotkriteria',
            name='kriteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dss.kriteria'),
        ),
        migrations.CreateModel(
            name='LaptopAlternatif',
            fields=[
                ('id_alternatif_laptop', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('model_alternatif', models.TextField()),
                ('brand_alternatif', models.TextField()),
                ('dss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.dssproses')),
            ],
            options={
                'db_table': 'dss_laptopalternatif',
            },
        ),
        migrations.CreateModel(
            name='LaptopPengadaan',
            fields=[
                ('id_laptop_pengadaan', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nama_laptop', models.CharField(max_length=255)),
                ('harga', models.IntegerField()),
                ('gpu', models.CharField(blank=True, max_length=255, null=True)),
                ('ukuran_layar', models.FloatField()),
                ('baterai', models.FloatField()),
                ('berat', models.FloatField()),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventori.processor')),
                ('ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventori.ram')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventori.storage')),
            ],
            options={
                'db_table': 'dss_laptoppengadaan',
            },
        ),
        migrations.CreateModel(
            name='NilaiAlternatif',
            fields=[
                ('id_nilai_alternatif', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nilai_alternatif', models.FloatField()),
<<<<<<< HEAD
                ('nilai_normalisasi', models.FloatField()),
                ('id_alternatif_laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.laptopalternatif')),
                ('id_bobot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.bobotkriteria')),
>>>>>>> origin/dev-lina
=======
>>>>>>> origin/dev-lina
            ],
        ),
        migrations.CreateModel(
            name='HasilSAW',
            fields=[
                ('id_hasil', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tanggal_proses', models.DateTimeField(auto_now_add=True)),
                ('id_dss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.dssproses')),
            ],
        ),
        migrations.CreateModel(
            name='DetailHasilSAW',
            fields=[
                ('id_detail', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nilai_normalisasi', models.FloatField()),
                ('nilai_preferensi', models.FloatField()),
                ('ranking', models.IntegerField()),
                ('id_hasil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_set', to='dss.hasilsaw')),
            ],
            options={
                'db_table': 'dss_detailhasilsaw',
            },
        ),
        migrations.AddField(
            model_name='bobotkriteria',
            name='id_kriteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.kriteria'),
        ),
        migrations.CreateModel(
            name='LaptopAlternatif',
            fields=[
                ('id_alternatif_laptop', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('model_alternatif', models.TextField()),
                ('brand_alternatif', models.TextField()),
                ('id_dss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.dssproses')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopPengadaan',
            fields=[
                ('id_laptop_pengadaan', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nama_laptop', models.CharField(max_length=255)),
                ('harga', models.IntegerField()),
                ('gpu', models.CharField(blank=True, max_length=255, null=True)),
                ('ukuran_layar', models.FloatField()),
                ('baterai', models.FloatField()),
                ('berat', models.FloatField()),
                ('id_processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventori.processor')),
                ('id_ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventori.ram')),
                ('id_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventori.storage')),
            ],
        ),
        migrations.CreateModel(
            name='NilaiAlternatif',
            fields=[
                ('id_nilai_alternatif', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nilai_alternatif', models.FloatField()),
                ('nilai_normalisasi', models.FloatField()),
                ('id_alternatif_laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.laptopalternatif')),
                ('id_bobot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.bobotkriteria')),
=======
                ('nilai_normalisasi', models.FloatField(blank=True, null=True)),
                ('alternatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.laptopalternatif')),
                ('bobot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.bobotkriteria')),
>>>>>>> origin/dev-alqan
            ],
            options={
                'db_table': 'dss_nilaialternatif',
            },
        ),
        migrations.AddField(
            model_name='hasilsaw',
<<<<<<< HEAD
            name='id_nilai_alternatif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dss.nilaialternatif'),
        ),
<<<<<<< HEAD
=======
                ('id_nilai_alternatif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dss.nilaialternatif')),
            ],
=======
            name='nilai_alternatif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dss.nilaialternatif'),
        ),
        migrations.AddIndex(
            model_name='bobotkriteria',
            index=models.Index(fields=['role_teknologi', 'is_active'], name='dss_bobotkr_role_te_d6d9a4_idx'),
>>>>>>> origin/dev-alqan
        ),
>>>>>>> origin/dev-lina
=======
>>>>>>> origin/dev-lina
    ]
