# Generated by Django 6.0.3 on 2026-04-11 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BobotKriteria',
            fields=[
                ('id_bobot', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('nilai_bobot', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id_kriteria', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nama_kriteria', models.CharField(max_length=255)),
                ('tipe_kriteria', models.CharField(choices=[('benefit', 'Benefit'), ('cost', 'Cost')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DSSProses',
            fields=[
                ('id_dss', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('role_dss', models.CharField(max_length=100)),
                ('jenis_dss', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bobot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.bobotkriteria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.user')),
            ],
        ),
        migrations.CreateModel(
            name='AlternatifDSS',
            fields=[
                ('id_alternatif', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id_laptop_pengadaan', models.CharField(blank=True, max_length=100, null=True)),
                ('sumber_data', models.CharField(max_length=100)),
                ('laptop_inventori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventori.laptopinventori')),
                ('dss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.dssproses')),
            ],
        ),
        migrations.CreateModel(
            name='HasilSAW',
            fields=[
                ('id_hasil', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tanggal_proses', models.DateTimeField(auto_now_add=True)),
                ('dss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.dssproses')),
            ],
        ),
        migrations.CreateModel(
            name='DetailHasilSAW',
            fields=[
                ('id_detail', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nilai_normalisasi', models.FloatField()),
                ('nilai_preferensi', models.FloatField()),
                ('ranking', models.IntegerField()),
                ('hasil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.hasilsaw')),
            ],
        ),
        migrations.AddField(
            model_name='bobotkriteria',
            name='kriteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.kriteria'),
        ),
    ]
