# Generated by Django 5.2.13 on 2026-05-29 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0001_initial'),
        ('inventori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternatifDSS',
            fields=[
                ('id_alternatif', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id_laptop_pengadaan', models.CharField(blank=True, max_length=100, null=True)),
                ('sumber_data', models.CharField(max_length=100)),
                ('dss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.dssproses')),
                ('laptop_inventori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventori.laptopinventori')),
            ],
            options={
                'db_table': 'dss_alternatifdss',
            },
        ),
        migrations.CreateModel(
            name='DetailHasilSAW',
            fields=[
                ('id_detail', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nilai_normalisasi', models.FloatField()),
                ('nilai_preferensi', models.FloatField()),
                ('ranking', models.IntegerField()),
                ('hasil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.hasilsaw')),
            ],
            options={
                'db_table': 'dss_detailhasilsaw',
            },
        ),
    ]
