# Generated by Django 6.0.3 on 2026-04-15 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0001_initial'),
        ('inventori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopPengadaan',
            fields=[
                ('id_laptop_pengadaan', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nama_laptop', models.CharField(max_length=255)),
                ('harga', models.IntegerField()),
                ('gpu', models.CharField(blank=True, max_length=255, null=True)),
                ('ukuran_layar', models.FloatField()),
                ('baterai', models.FloatField()),
                ('berat', models.FloatField()),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventori.processor')),
                ('ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventori.ram')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventori.storage')),
            ],
        ),
    ]
