# Generated by Django 6.0.3 on 2026-04-27 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailHasilSAW',
            fields=[
                ('id_detail', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nilai_normalisasi', models.FloatField()),
                ('nilai_preferensi', models.FloatField()),
                ('ranking', models.IntegerField()),
                ('id_hasil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_set', to='dss.hasilsaw')),
            ],
            options={
                'db_table': 'dss_detailhasilsaw',
            },
        ),
    ]
