# Generated by Django 5.2.13 on 2026-06-13 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailhasilsaw',
            name='hasil',
            field=models.ForeignKey(db_column='id_hasil', on_delete=django.db.models.deletion.CASCADE, to='dss.hasilsaw'),
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='golongan_kriteria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
