# Generated by Django 6.0.4 on 2026-06-17 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0003_alter_detailhasilsaw_hasil_and_more'),
        ('inventori', '0005_alter_teknologirole_role_proyek_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobotkriteria',
            name='nilai_swara',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bobotkriteria',
            name='id_kriteria',
            field=models.ForeignKey(db_column='kriteria_id', on_delete=django.db.models.deletion.CASCADE, to='dss.kriteria'),
        ),
        migrations.AlterField(
            model_name='dssproses',
            name='id_bobot',
            field=models.ForeignKey(db_column='bobot_id', on_delete=django.db.models.deletion.CASCADE, to='dss.bobotkriteria'),
        ),
        migrations.AlterField(
            model_name='dssproses',
            name='id_user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='inventori.user'),
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='golongan_kriteria',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='laptoppengadaan',
            name='id_processor',
            field=models.ForeignKey(blank=True, db_column='processor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventori.processor'),
        ),
        migrations.AlterField(
            model_name='laptoppengadaan',
            name='id_ram',
            field=models.ForeignKey(blank=True, db_column='ram_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventori.ram'),
        ),
        migrations.AlterField(
            model_name='laptoppengadaan',
            name='id_storage',
            field=models.ForeignKey(blank=True, db_column='storage_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventori.storage'),
        ),
    ]
