<<<<<<< HEAD
# Generated by Django 6.0.4 on 2026-05-02 01:32
=======
# Generated by Django 5.2.13 on 2026-04-29 06:09
>>>>>>> origin/dev-lina

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id_processor', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nama_processor', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('cores', models.IntegerField()),
                ('threads', models.IntegerField()),
                ('base_clock', models.FloatField()),
                ('max_clock', models.FloatField()),
                ('arsitektur', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id_ram', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('kapasitas_gb', models.IntegerField()),
                ('tipe', models.CharField(max_length=50)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id_storage', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('kapasitas_gb', models.IntegerField()),
                ('tipe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopInventori',
            fields=[
                ('id_laptop_inventori', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('no_inventori', models.CharField(max_length=100, unique=True)),
                ('nama_laptop', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=100)),
                ('kondisi', models.CharField(choices=[('baik', 'Baik'), ('rusak_ringan', 'Rusak Ringan'), ('rusak_berat', 'Rusak Berat')], max_length=50)),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('dipinjam', 'Dipinjam'), ('rusak', 'Rusak')], max_length=50)),
                ('lokasi', models.CharField(max_length=255)),
                ('ukuran_layar', models.FloatField(blank=True, null=True)),
                ('id_processor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventori.processor')),
                ('id_ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventori.ram')),
                ('id_storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventori.storage')),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatAktivitas',
            fields=[
                ('id_aktivitas', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('jenis_aktivitas', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_laptop_inventori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.laptopinventori')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.user')),
            ],
        ),
        migrations.CreateModel(
            name='Pengajuan',
            fields=[
                ('id_pengajuan', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('kebutuhan_role', models.CharField(max_length=100)),
                ('kebutuhan_requirement', models.TextField()),
                ('bulan', models.DateField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('perusahaan', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('tanggal_approval', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to='inventori.user')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.user')),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id_peminjaman', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tanggal_pinjam', models.DateField()),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('id_laptop_inventori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.laptopinventori')),
                ('id_pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.pengajuan')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.user')),
            ],
        ),
    ]
