# Generated by Django 6.0.6 on 2026-06-11 03:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id_processor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_processor', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('cores', models.IntegerField()),
                ('threads', models.IntegerField()),
                ('base_clock', models.FloatField()),
                ('max_clock', models.FloatField()),
                ('arsitektur', models.CharField(max_length=100)),
                ('benchmark_score', models.IntegerField(default=0)),
                ('benchmark_url', models.TextField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventori_processor',
            },
        ),
        migrations.CreateModel(
            name='Proyek',
            fields=[
                ('id_proyek', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_proyek', models.CharField(max_length=255)),
                ('user_perusahaan', models.CharField(max_length=255)),
                ('mulai_proyek', models.DateField()),
                ('akhir_proyek', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventori_proyek',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id_ram', models.BigAutoField(db_column='id_ram', primary_key=True, serialize=False)),
                ('kapasitas_gb', models.IntegerField()),
                ('tipe', models.CharField(max_length=50)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_role', models.CharField(max_length=100, unique=True)),
                ('min_ram', models.IntegerField(default=0)),
                ('min_storage', models.IntegerField(default=0)),
                ('min_processor_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'inventori_role',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id_storage', models.BigAutoField(db_column='id_', primary_key=True, serialize=False)),
                ('kapasitas_gb', models.IntegerField()),
                ('tipe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teknologi',
            fields=[
                ('id_teknologi', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_teknologi', models.CharField(max_length=100, unique=True)),
                ('kategori', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'inventori_teknologi',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopInventori',
            fields=[
                ('id_laptop_inventori', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('no_inventori', models.CharField(max_length=100, unique=True)),
                ('nama_laptop', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=100)),
                ('kondisi', models.CharField(choices=[('baik', 'Baik'), ('rusak_ringan', 'Rusak Ringan'), ('rusak_berat', 'Rusak Berat')], max_length=50)),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('dipinjam', 'Dipinjam'), ('rusak', 'Rusak')], max_length=50)),
                ('lokasi', models.CharField(max_length=255)),
                ('ukuran_layar', models.FloatField(blank=True, null=True)),
                ('id_processor', models.ForeignKey(db_column='id_processor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventori.processor')),
                ('id_ram', models.ForeignKey(db_column='id_ram', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventori.ram')),
                ('id_storage', models.ForeignKey(db_column='id_storage', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventori.storage')),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatAktivitas',
            fields=[
                ('id_aktivitas', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('jenis_aktivitas', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_laptop_inventori', models.ForeignKey(db_column='laptop_id', on_delete=django.db.models.deletion.CASCADE, to='inventori.laptopinventori')),
                ('id_user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='inventori.user')),
            ],
        ),
        migrations.CreateModel(
            name='Pengajuan',
            fields=[
                ('id_pengajuan', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('kebutuhan_role', models.CharField(max_length=100)),
                ('kebutuhan_requirement', models.TextField()),
                ('bulan', models.DateField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('perusahaan', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('tanggal_approval', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(db_column='approved_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to='inventori.user')),
                ('id_user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='inventori.user')),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id_peminjaman', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tanggal_pinjam', models.DateField()),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('id_laptop_inventori', models.ForeignKey(db_column='laptop_id', on_delete=django.db.models.deletion.CASCADE, to='inventori.laptopinventori')),
                ('id_pengajuan', models.ForeignKey(db_column='pengajuan_id', on_delete=django.db.models.deletion.CASCADE, to='inventori.pengajuan')),
                ('id_user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='inventori.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id_project_role', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('persentase_role', models.FloatField()),
                ('proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.proyek')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.role')),
            ],
            options={
                'db_table': 'inventori_project_role',
                'unique_together': {('proyek', 'role')},
            },
        ),
        migrations.CreateModel(
            name='RoleTeknologi',
            fields=[
                ('id_role_teknologi', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.role')),
                ('teknologi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.teknologi')),
            ],
            options={
                'db_table': 'role_teknologi',
                'unique_together': {('role', 'teknologi')},
            },
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id_project_technology', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.proyek')),
                ('teknologi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.teknologi')),
            ],
            options={
                'db_table': 'inventori_project_teknologi',
                'unique_together': {('proyek', 'teknologi')},
            },
        ),
    ]
