# Generated by Django 5.2.13 on 2026-06-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyek',
            fields=[
                ('id_proyek', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nama_proyek', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('teknologi', models.TextField()),
            ],
        ),
    ]
