# Generated by Django 6.0.4 on 2026-05-16 10:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyek',
            fields=[
                ('id_proyek', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_proyek', models.CharField(max_length=255)),
                ('user_perusahaan', models.CharField(max_length=255)),
                ('mulai_proyek', models.DateField()),
                ('akhir_proyek', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventori_proyek',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_role', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'inventori_role',
            },
        ),
        migrations.CreateModel(
            name='Teknologi',
            fields=[
                ('id_teknologi', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_teknologi', models.CharField(max_length=100, unique=True)),
                ('kategori', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'inventori_teknologi',
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id_project_role', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('persentase_role', models.FloatField()),
                ('proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.proyek')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.role')),
            ],
            options={
                'db_table': 'inventori_project_role',
                'unique_together': {('proyek', 'role')},
            },
        ),
        migrations.CreateModel(
            name='RoleTeknologi',
            fields=[
                ('id_role_teknologi', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.role')),
                ('teknologi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.teknologi')),
            ],
            options={
                'db_table': 'role_teknologi',
                'unique_together': {('role', 'teknologi')},
            },
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id_project_technology', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.proyek')),
                ('teknologi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.teknologi')),
            ],
            options={
                'db_table': 'inventori_project_teknologi',
                'unique_together': {('proyek', 'teknologi')},
            },
        ),
    ]
