# Generated by Django 5.2.13 on 2026-06-13 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventori', '0002_proyek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyek',
            name='role',
        ),
        migrations.RemoveField(
            model_name='proyek',
            name='teknologi',
        ),
        migrations.CreateModel(
            name='RoleProyek',
            fields=[
                ('id_role', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nama_role', models.CharField(max_length=255)),
                ('proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='inventori.proyek')),
            ],
        ),
        migrations.CreateModel(
            name='TeknologiRole',
            fields=[
                ('id_teknologi', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nama_teknologi', models.CharField(max_length=255)),
                ('role_proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teknologi', to='inventori.roleproyek')),
            ],
        ),
    ]
