# Generated by Django 6.0.4 on 2026-06-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventori', '0002_remove_processor_benchmark_url_and_more'),
        ('inventori', '0003_remove_proyek_role_remove_proyek_teknologi_and_more'),
    ]

    operations = [
    ]
