# Generated by Django 6.0.4 on 2026-06-17 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventori', '0004_merge_20260615_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teknologirole',
            name='role_proyek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teknologi', to='inventori.projectrole'),
        ),
        migrations.AlterUniqueTogether(
            name='projectrole',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='processor',
            name='benchmark_url',
        ),
        migrations.RemoveField(
            model_name='proyek',
            name='role',
        ),
        migrations.RemoveField(
            model_name='proyek',
            name='teknologi',
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='proyek',
            field=models.ForeignKey(db_column='id_proyek', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='inventori.proyek'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='role',
            field=models.ForeignKey(db_column='id_role', on_delete=django.db.models.deletion.CASCADE, to='inventori.role'),
        ),
        migrations.AlterField(
            model_name='roleteknologi',
            name='role',
            field=models.ForeignKey(db_column='id_role', on_delete=django.db.models.deletion.CASCADE, related_name='teknologi_role', to='inventori.role'),
        ),
        migrations.DeleteModel(
            name='RoleProyek',
        ),
    ]
